#??????
spring:
  #Mysql?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/temp_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
#    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #???????????????????????
      initial-size: 5 #???????????
      min-idle: 5 #?????
      max-active: 20  #??
      max-wait: 60000 #?????????????
      time-between-eviction-runs-millis: 60000 #???????????????????????????????
      min-evictable-idle-time-millis: 300000  #??????????????????????
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true  #??PSCache??????????PSCache???
      max-pool-prepared-statement-per-connection-size: 20 #?????????filters????????sql?????'wall'?????
      filters: stat,wall
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  #??connectProperties?????mergeSql????SQL??
      #???????
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        url-pattern: /* #??????
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #??????



mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/../../mapper/*.xml
  type-aliases-package: com.person.study.entity


logging:
  config: classpath:logback-spring.xml